server:
  port : 8387
  
# Oracle Connect
spring:

  # File Size (이미지 올릴 때 사용)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # DB 연결 (JDBC)
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger
      
  # JPA Setting
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

  # View Resolver (View단 지정하기. 안 하면 templates으로 자동으로 가니까)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  #Gmail Transfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: amazing9.code@gmail.com
    password: yseb ubdt bcfq krrx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
  
# logger를 통해 hibernate 실행        
logging.level:
  org.hibernate.SQL: debug
